include:
   - project: nse/ci
     file:
        - /ci/lib/tox-bb5.yml
        - /ci/jobs/check-version.yml
        - /ci/jobs/lint.yml
        - /ci/jobs/py36.yml
        - /ci/jobs/py37.yml
        - /ci/jobs/py38.yml
        - /ci/jobs/docs.yml
